
[settings]

	[settings.other]
		chat_prefix = "&8[&a&lSpot&r&2&oPlaying&r&8]&r &f"

	[settings.configuration]
		api_ping_rate = "5000"

	[settings.api_access]
		spotify_user_id = ""
		discord_token = ""
		spotify_token = ""
		spotify_device_id = ""

[now_playing]

	[now_playing.-_toggles_-]
		overlay_enabled = false
		player_controls = true
		middle_click_to_open_spotify = true
		progress_bar = true

	[now_playing.configuration]
		song_title_text = "{song}"
		text_shadows = true
		overlay_color = "255,0,0,0"
		"&e&oprogress_bar_text" = "&a{minutes}:{seconds} / {endminutes}:{endseconds}"
		"&e&oprogress_bar_opacity" = 200
		overlay_opacity = 100
		artist_title_text = "&7{artist}"
		"&e&oprogress_bar_color" = "255,0,0,0"

	[now_playing.position]
		"&e&osnap_size" = 5
		"&e&ooverlay_x" = 5
		"&e&ooverlay_y" = 5

